#!/usr/bin/env python3
"""
ToxShield Instagram Reel video generator using FFmpeg.

Takes a directory of PNG carousel slides (generated by generate_carousel.py
or any other generator) and produces an MP4 video with smooth crossfade
transitions, suitable for publishing as an Instagram Reel.

Requirements:
    - FFmpeg >= 5.0 (brew install ffmpeg)
    - Pillow (for slide validation)

Usage:
    # Basic: crossfade from carousel slides
    python scripts/instagram/generate_reel.py \
        --slides-dir output/instagram/2026-03-25/toxic_callout/

    # With custom timing and audio
    python scripts/instagram/generate_reel.py \
        --slides-dir output/instagram/2026-03-25/toxic_callout/ \
        --slide-duration 4 --crossfade 1.0 \
        --audio output/instagram/audio/track.mp3 --audio-volume 0.3

    # Ken Burns (slow zoom) effect
    python scripts/instagram/generate_reel.py \
        --slides-dir output/instagram/2026-03-25/toxic_callout/ \
        --transition kenburns
"""

from __future__ import annotations

import argparse
import json
import logging
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).parent.parent.parent

# ===========================================================================
# Constants
# ===========================================================================

DEFAULT_WIDTH = 1080
DEFAULT_HEIGHT = 1350  # 4:5 portrait (auto-detected from slides)
FRAMERATE = 30
DEFAULT_SLIDE_DURATION = 8  # seconds per slide (targets 45-60s Shorts)
DEFAULT_CROSSFADE_DURATION = 1.0  # seconds of crossfade overlap
MIN_SLIDES = 3
MAX_SLIDES = 10


# ===========================================================================
# Reel Generator
# ===========================================================================

class ReelGenerator:
    """Generate an MP4 Reel video from a directory of PNG carousel slides."""

    def __init__(
        self,
        slides_dir: str,
        output_path: Optional[str] = None,
        slide_duration: float = DEFAULT_SLIDE_DURATION,
        crossfade_duration: float = DEFAULT_CROSSFADE_DURATION,
        transition: str = "crossfade",
        audio_path: Optional[str] = None,
        audio_volume: float = 0.8,
        slide_durations: Optional[List[float]] = None,
        max_slides: int = MAX_SLIDES,
        audio_loop: bool = False,
    ):
        self.slides_dir = Path(slides_dir)
        self.slide_duration = slide_duration
        self.crossfade_duration = crossfade_duration
        self.transition = transition
        self.audio_path = Path(audio_path) if audio_path else None
        self.audio_volume = max(0.0, min(1.0, audio_volume))
        self.slide_durations = slide_durations  # Per-slide durations (overrides slide_duration)
        self.max_slides = max_slides
        self.audio_loop = audio_loop  # Loop audio for long-form videos

        self.width = DEFAULT_WIDTH
        self.height = DEFAULT_HEIGHT

        if output_path:
            self.output_path = Path(output_path)
        else:
            self.output_path = self.slides_dir / "reel.mp4"

    def _get_slide_duration(self, index: int) -> float:
        """Get duration for a specific slide (uses per-slide durations if set)."""
        if self.slide_durations and index < len(self.slide_durations):
            return self.slide_durations[index]
        return self.slide_duration

    def _get_total_duration(self, num_slides: int) -> float:
        """Calculate total video duration accounting for crossfades."""
        total = sum(self._get_slide_duration(i) for i in range(num_slides))
        total -= (num_slides - 1) * self.crossfade_duration
        return total

    def _check_ffmpeg(self) -> str:
        """Verify FFmpeg is installed and return its path."""
        ffmpeg = shutil.which("ffmpeg")
        if not ffmpeg:
            logger.error("FFmpeg not found. Install it: brew install ffmpeg")
            sys.exit(1)

        try:
            result = subprocess.run(
                [ffmpeg, "-version"],
                capture_output=True, text=True, timeout=10,
            )
            version_line = result.stdout.split("\n")[0]
            logger.info(f"Found {version_line}")
        except (subprocess.TimeoutExpired, FileNotFoundError):
            logger.error("FFmpeg not responding")
            sys.exit(1)

        return ffmpeg

    def _collect_slides(self) -> List[Path]:
        """Collect PNG slides from the directory, sorted by name."""
        if not self.slides_dir.is_dir():
            logger.error(f"Slides directory not found: {self.slides_dir}")
            sys.exit(1)

        slides = sorted(self.slides_dir.glob("*.png"))

        # Filter out any non-slide files (e.g., thumbnails)
        slides = [s for s in slides if s.stem.startswith("slide_")]
        if not slides:
            # Fallback: use all PNGs if no slide_* pattern
            slides = sorted(self.slides_dir.glob("*.png"))

        return slides

    def _validate_slides(self, slides: List[Path]) -> None:
        """Validate slide count and auto-detect dimensions from first slide."""
        if len(slides) < MIN_SLIDES:
            logger.error(f"Need at least {MIN_SLIDES} slides, found {len(slides)}")
            sys.exit(1)
        if len(slides) > self.max_slides:
            logger.warning(f"Found {len(slides)} slides, using first {self.max_slides}")

        try:
            from PIL import Image
            # Auto-detect dimensions from first slide
            with Image.open(slides[0]) as img:
                self.width, self.height = img.size
                logger.info(f"Auto-detected slide dimensions: {self.width}x{self.height}")

            for slide in slides[1:self.max_slides]:
                with Image.open(slide) as img:
                    w, h = img.size
                    if w != self.width or h != self.height:
                        logger.warning(
                            f"{slide.name}: {w}x{h} (expected {self.width}x{self.height}), "
                            "FFmpeg will scale to fit"
                        )
        except ImportError:
            logger.warning("Pillow not available, skipping dimension validation")

    def _build_crossfade_filter(self, num_slides: int) -> str:
        """Build FFmpeg filter_complex for crossfade transitions.

        Supports both uniform and per-slide durations. For each transition i,
        the offset is the cumulative duration of slides 0..i minus cumulative
        crossfade time.
        """
        if num_slides < 2:
            return ""

        filters = []
        for i in range(num_slides - 1):
            # Cumulative duration of slides 0 through i+1, minus crossfade overlaps
            cumulative = sum(self._get_slide_duration(j) for j in range(i + 1))
            offset = cumulative - (i + 1) * self.crossfade_duration

            if i == 0:
                input_a = f"[{i}]"
            else:
                input_a = f"[x{i - 1:02d}]"

            input_b = f"[{i + 1}]"

            if i == num_slides - 2:
                output = "[video]"
            else:
                output = f"[x{i:02d}]"

            filters.append(
                f"{input_a}{input_b}xfade=transition=fade:"
                f"duration={self.crossfade_duration}:offset={offset}{output}"
            )

        return ";".join(filters)

    def _build_kenburns_filter(self, num_slides: int) -> str:
        """Build FFmpeg filter_complex for Ken Burns (zoom pan) + crossfade.

        Each slide gets a subtle zoom effect via zoompan, then crossfade
        transitions between the zoomed outputs.
        """
        if num_slides < 2:
            return ""

        filters = []

        # Step 1: Apply zoompan to each slide
        for i in range(num_slides):
            frames_per_slide = int(self._get_slide_duration(i) * FRAMERATE)
            # Alternate between zoom-in and zoom-out for variety
            if i % 2 == 0:
                zoom = f"min(zoom+0.0008,1.3)"
                x = f"iw/2-(iw/zoom/2)"
                y = f"ih/2-(ih/zoom/2)"
            else:
                zoom = f"if(eq(on,1),1.3,max(zoom-0.0008,1))"
                x = f"iw/2-(iw/zoom/2)"
                y = f"ih/2-(ih/zoom/2)"

            filters.append(
                f"[{i}]zoompan=z='{zoom}':"
                f"x='{x}':y='{y}':"
                f"d={frames_per_slide}:s={self.width}x{self.height}:"
                f"fps={FRAMERATE}[z{i}]"
            )

        # Step 2: Crossfade between zoompan outputs
        for i in range(num_slides - 1):
            cumulative = sum(self._get_slide_duration(j) for j in range(i + 1))
            offset = cumulative - (i + 1) * self.crossfade_duration

            if i == 0:
                input_a = f"[z{i}]"
            else:
                input_a = f"[x{i - 1:02d}]"

            input_b = f"[z{i + 1}]"

            if i == num_slides - 2:
                output = "[video]"
            else:
                output = f"[x{i:02d}]"

            filters.append(
                f"{input_a}{input_b}xfade=transition=fade:"
                f"duration={self.crossfade_duration}:offset={offset}{output}"
            )

        return ";".join(filters)

    def _build_ffmpeg_command(self, ffmpeg: str, slides: List[Path]) -> List[str]:
        """Construct the full FFmpeg command."""
        num_slides = len(slides)
        cmd = [ffmpeg, "-y"]  # -y to overwrite output

        # Input: each slide as a looped image (with per-slide duration)
        for i, slide in enumerate(slides):
            duration = self._get_slide_duration(i)
            cmd.extend([
                "-loop", "1",
                "-t", str(duration),
                "-framerate", str(FRAMERATE),
                "-i", str(slide),
            ])

        # Audio input
        audio_input_index = num_slides
        if self.audio_path and self.audio_path.exists():
            if self.audio_loop:
                cmd.extend(["-stream_loop", "-1", "-i", str(self.audio_path)])
            else:
                cmd.extend(["-i", str(self.audio_path)])
        else:
            # Silent audio track
            cmd.extend([
                "-f", "lavfi",
                "-i", f"anullsrc=r=44100:cl=stereo",
            ])

        # Build filter complex
        if self.transition == "kenburns":
            filter_str = self._build_kenburns_filter(num_slides)
        else:
            filter_str = self._build_crossfade_filter(num_slides)

        if filter_str:
            # For long-form (many slides), write filter to temp file to avoid arg length limits
            if num_slides > 20:
                import tempfile
                filter_file = Path(tempfile.mktemp(suffix=".txt"))
                filter_file.write_text(filter_str)
                cmd.extend(["-filter_complex_script", str(filter_file)])
            else:
                cmd.extend(["-filter_complex", filter_str])
            cmd.extend(["-map", "[video]"])
        else:
            cmd.extend(["-map", "0:v"])

        # Audio mapping
        cmd.extend(["-map", f"{audio_input_index}:a"])
        if self.audio_path and self.audio_path.exists():
            cmd.extend(["-af", f"volume={self.audio_volume}"])

        # Output encoding
        total_duration = self._get_total_duration(num_slides)
        preset = "fast" if num_slides > 20 else "medium"
        cmd.extend([
            "-c:v", "libx264",
            "-preset", preset,
            "-crf", "23",
            "-pix_fmt", "yuv420p",
            "-c:a", "aac",
            "-b:a", "128k",
            "-shortest",
            "-t", str(total_duration),
            "-movflags", "+faststart",
            str(self.output_path),
        ])

        return cmd

    def _verify_output(self) -> bool:
        """Verify the output video file exists and has reasonable size."""
        if not self.output_path.exists():
            return False

        size_kb = self.output_path.stat().st_size / 1024
        if size_kb < 100:
            logger.error(f"Output file too small ({size_kb:.0f}KB), likely corrupt")
            return False

        size_mb = size_kb / 1024
        logger.info(f"Output: {self.output_path} ({size_mb:.1f}MB)")
        return True

    def generate(self) -> Path:
        """Generate the Reel video. Returns the output path."""
        # Step 1: Check FFmpeg
        ffmpeg = self._check_ffmpeg()

        # Step 2: Collect and validate slides
        slides = self._collect_slides()
        slides = slides[:self.max_slides]
        self._validate_slides(slides)

        num_slides = len(slides)
        total_duration = self._get_total_duration(num_slides)

        logger.info(f"Generating video: {num_slides} slides, {total_duration:.1f}s duration")
        logger.info(f"Transition: {self.transition}, slide duration: {self.slide_duration}s")
        if self.slide_durations:
            logger.info(f"Per-slide durations: {[self._get_slide_duration(i) for i in range(num_slides)]}")
        if self.audio_path:
            logger.info(f"Audio: {self.audio_path} (volume: {self.audio_volume}, loop: {self.audio_loop})")
        else:
            logger.info("Audio: silent track")

        # Step 3: Ensure output directory exists
        self.output_path.parent.mkdir(parents=True, exist_ok=True)

        # Step 4: Build and run FFmpeg
        cmd = self._build_ffmpeg_command(ffmpeg, slides)
        logger.info(f"Running FFmpeg...")
        logger.debug(f"Command: {' '.join(cmd)}")

        # Longer timeout for long-form videos (30 min vs 5 min)
        timeout = 1800 if total_duration > 120 else 300

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            if result.returncode != 0:
                logger.error(f"FFmpeg failed (exit {result.returncode}):")
                stderr_lines = result.stderr.strip().split("\n")
                for line in stderr_lines[-20:]:
                    logger.error(f"  {line}")
                sys.exit(1)
        except subprocess.TimeoutExpired:
            logger.error(f"FFmpeg timed out after {timeout // 60} minutes")
            sys.exit(1)

        # Step 5: Verify output
        if not self._verify_output():
            logger.error("Output verification failed")
            sys.exit(1)

        logger.info(f"Video generated successfully: {self.output_path}")
        return self.output_path


# ===========================================================================
# CLI
# ===========================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Generate Instagram Reel video from carousel slides"
    )
    parser.add_argument(
        "--slides-dir", "-s", required=True,
        help="Directory containing PNG carousel slides",
    )
    parser.add_argument(
        "--output", "-o",
        help="Output MP4 path (default: <slides-dir>/reel.mp4)",
    )
    parser.add_argument(
        "--slide-duration", type=float, default=DEFAULT_SLIDE_DURATION,
        help=f"Seconds per slide (default: {DEFAULT_SLIDE_DURATION})",
    )
    parser.add_argument(
        "--crossfade", type=float, default=DEFAULT_CROSSFADE_DURATION,
        help=f"Crossfade duration in seconds (default: {DEFAULT_CROSSFADE_DURATION})",
    )
    parser.add_argument(
        "--transition", "-t", choices=["crossfade", "kenburns"],
        default="crossfade",
        help="Transition type (default: crossfade)",
    )
    parser.add_argument(
        "--audio", "-a",
        help="Path to background audio file (optional)",
    )
    parser.add_argument(
        "--mood", "-m",
        choices=["dark-ambient", "tension", "empowering", "trending-beat"],
        help="Auto-select background track by mood (overridden by --audio)",
    )
    parser.add_argument(
        "--audio-volume", type=float, default=0.8,
        help="Audio volume 0.0-1.0 (default: 0.8)",
    )
    parser.add_argument(
        "--narration-dir", "-n",
        help="Directory containing narration clips and timing.json (from generate_narration.py)",
    )
    parser.add_argument(
        "--narration-volume", type=float, default=1.0,
        help="Narration audio volume 0.0-1.0 (default: 1.0)",
    )

    args = parser.parse_args()

    # Narration mode: load timing.json and use narration as audio
    slide_durations = None
    narration_audio = None

    if args.narration_dir:
        narration_dir = Path(args.narration_dir)
        timing_file = narration_dir / "timing.json"

        if not timing_file.exists():
            logger.error(f"timing.json not found in narration dir: {narration_dir}")
            sys.exit(1)

        with open(timing_file) as f:
            timing = json.load(f)

        narration_audio = str(narration_dir / timing["full_narration"])
        slide_durations = timing["slide_durations"]

        if not Path(narration_audio).exists():
            logger.error(f"Narration audio not found: {narration_audio}")
            sys.exit(1)

        logger.info(f"Narration mode: {len(slide_durations)} slides, "
                     f"per-slide durations: {slide_durations}")
        logger.info(f"Narration audio: {narration_audio}")

    # Resolve audio: narration > --audio > --mood
    audio_path = narration_audio or args.audio
    audio_volume = args.narration_volume if narration_audio else args.audio_volume

    if not audio_path and args.mood:
        try:
            from download_music import get_track_for_mood
            audio_path = get_track_for_mood(args.mood)
            if audio_path:
                logger.info(f"Selected {args.mood} track: {audio_path}")
            else:
                logger.warning(f"No {args.mood} track found. Run: python3 scripts/instagram/download_music.py --generate-synthetic")
        except ImportError:
            # Try direct import from same directory
            script_dir = Path(__file__).parent
            sys.path.insert(0, str(script_dir))
            try:
                from download_music import get_track_for_mood
                audio_path = get_track_for_mood(args.mood)
                if audio_path:
                    logger.info(f"Selected {args.mood} track: {audio_path}")
                else:
                    logger.warning(f"No {args.mood} track found. Run: python3 scripts/instagram/download_music.py --generate-synthetic")
            except ImportError:
                logger.warning("download_music.py not found, skipping mood-based audio selection")

    generator = ReelGenerator(
        slides_dir=args.slides_dir,
        output_path=args.output,
        slide_duration=args.slide_duration,
        crossfade_duration=args.crossfade,
        transition=args.transition,
        audio_path=audio_path,
        audio_volume=audio_volume,
        slide_durations=slide_durations,
    )

    output_path = generator.generate()

    # Machine-readable output
    num_slides = len(list(Path(args.slides_dir).glob("*.png")))
    if slide_durations:
        total_duration = sum(slide_durations) - (num_slides - 1) * args.crossfade
    else:
        total_duration = num_slides * args.slide_duration - (num_slides - 1) * args.crossfade
    print(f"\n{json.dumps({
        'output': str(output_path),
        'duration': round(total_duration, 1),
        'slides': num_slides,
        'transition': args.transition,
        'narrated': bool(narration_audio),
        'size_mb': round(output_path.stat().st_size / 1024 / 1024, 1),
    })}")


if __name__ == "__main__":
    main()
